# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('success', models.BooleanField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('url', models.TextField()),
                ('outfile', models.TextField()),
            ],
            options={
                'db_table': 'downloads',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('realm', models.CharField(blank=True, max_length=50, null=True)),
                ('success', models.IntegerField(blank=True, null=True)),
                ('input', models.TextField()),
            ],
            options={
                'db_table': 'input',
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.IntegerField()),
                ('ip', models.CharField(max_length=15, null=True)),
                ('termsize', models.CharField(blank=True, max_length=7, null=True)),
                ('client', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='Ttylog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=32)),
                ('ttylog', models.TextField()),
            ],
            options={
                'db_table': 'ttylog',
            },
        ),
        migrations.AddField(
            model_name='auth',
            name='ip_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='honey.Sessions'),
        ),
    ]
