# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('honey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='ip_key',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='honey.Sessions'),
        ),
    ]
